### ISSUE TITLE
When devices have same hostname, they don't show up

### ISSUE THREAD

**Issue by nunojpg** [wellenvogel/BonjourBrowser#1]
I noticed that I could not see some of my devices in this app. Then I tried with a Python script I use on the PC with ServiceBrowser and Zeroconf. It also failed.

I noticed hostname resolution was failing and I was handling that. 

The reason was that several devices had the same hostname on the network.

So in some way I suspect you have the same issue. More, you don't show hostnames, so if you are resolving them this is the reason why the app is very slow in updating the results. If you can disable it in Java then you also improve the speed.

**Comment by wellenvogel** [comment]
Thanks for your input.
I will have a look at it again - but at the end I have to rely on the interfaces that android provides.
As far as I see there is only one interface that will get me the service details that I need for display.
And at the end for the use case the hostname has to be resolved anyway - otherwise the browser will not be able to connect anyway.

**Comment by nunojpg** [comment]
Thanks!

Yes and no.

Yes - you depend on Android interfaces. I don't know which one they are.

No - hostname does not have to be resolved - you can connect over IP address alone.

**Comment by wellenvogel** [comment]
Completely agree - but I guess finally it's more the other way around - the first known piece is the service name and afterwards this must be resolved. I have no idea how exactly they do this internally and why the need the hostname at all.
But as I said - all hidden behind the android APIs

**Comment by nunojpg** [comment]
I took a look at the android API and in fact I don't see anything you can do :/ Thanks
